defaults:
  - base_config
exp_name: act_5111
policy: BC_ACT
gpu: 0

net_cfg:
  checkpoint_path: /data1/jiangranlv/code/cutting_paper_fem/rloutputs/exp/ac_fix_open/version_1/checkpoints/epoch=21-step=140000.ckpt
  model_yaml_path: /data1/jiangranlv/code/cutting_paper_fem/rloutputs/exp/ac_fix_open/version_1/model_config.yaml
  seq_len: 4
  pose_dim: 6
  gpuid: 0

max_timesteps: 50
chunking_weight: [0.05, 0.1, 0.1, 1.0]
val_set: /home/jiangranlv/code/cutting_paper_fem/test_val_set.txt



