defaults:
  - base_config
exp_name: debug
policy: PoseBC
gpu: 0

net_cfg:
  checkpoint_path: /data1/jiangranlv/code/cutting_paper_fem/rloutputs/exp/pose_fix_open/version_0/checkpoints/epoch=16-step=140000.ckpt
  model_yaml_path: /data1/jiangranlv/code/cutting_paper_fem/rloutputs/exp/pose_fix_open/version_0/model_config.yaml
  seq_len: 4
  pose_dim: 6
  gpuid: 0


val_set: /home/jiangranlv/code/cutting_paper_fem/test_val_set.txt



