PN_cfg:
  set_abstraction1_cfg:
    npoint: 256
    radius_list:
    - 0.1
    - 0.2
    - 0.4
    nsample_list:
    - 16
    - 32
    - 64
    in_channel: 1
    mlp_list:
    - - 32
      - 32
      - 64
    - - 64
      - 64
      - 128
    - - 64
      - 96
      - 128
  set_abstraction2_cfg:
    npoint: 64
    radius_list:
    - 0.2
    - 0.4
    - 0.8
    nsample_list:
    - 16
    - 32
    - 64
    in_channel: 320
    mlp_list:
    - - 64
      - 64
      - 128
    - - 128
      - 128
      - 256
    - - 128
      - 128
      - 256
  set_abstraction3_cfg:
    npoint: null
    radius: null
    nsample: null
    in_channel: 643
    mlp:
    - 256
    - 512
    - 1024
    group_all: true
  hidden_dim:
  - 512
  - 512
pn_output_dim: 512
seq_len: 4
chunking_size: 4
pose_tokenizer_cfg:
  hidden_dim:
  - 64
pose_input_dim: 6
pose_token_dim: 64
action_detokenizer_cfg:
  rot_head_cfg:
    hidden_dim:
    - 256
    - 64
  trans_head_cfg:
    hidden_dim:
    - 256
    - 64
  angle_head_cfg:
    hidden_dim:
    - 256
    - 64
PE_cfg:
  dropout: 0.1
  max_len: 1000
transformer_cfg:
  layer:
    nhead: 8
    dim_feedforward: 256
  num_layers: 3
action_loss_cfg:
  angle_weight: 1.0
  translation_weight: 10
  rotation_weight: 1.0
  angle_loss: l2
  translation_loss: l2
  rotation_loss: l1

helper_net_cfg:
  output_dim: 32
  hidden_dim:
  - 256
  - 256
helper_loss_cfg:
  loss_name: chamfer_distance
  weight: 0
  chamfer_distance_p: 1
input_statistics:
  point_cloud:
    mean: [0.08134385, 0.0046094, 0.15284023, 0.]
    std: [0.07464645, 0.07464645, 0.07464645, 1.]
  scissor_pose:
    mean: [-0.09131761, 0.02888361, 0.03622385, 0.14638498, 0.16358851, 0.0074226, 0.16835716, 0.14005724]
    std: [0.18268688, 0.10507938, 0.12708044, 0.0675601, 0.19768135, 0.20669429, 0.6547538, 0.6439879 ]
  action:
    translation:
      mean: [0.03259763, -0.00670006, 0.00247545]
      std: [0.04390685, 0.04390685, 0.04390685]

no_pose: False