PN_cfg:
  set_abstraction1_cfg:
    npoint: 256
    radius_list: [0.1, 0.2, 0.4]
    nsample_list: [16, 32, 64]
    in_channel: 1
    mlp_list: [[16, 16, 32], [32, 32, 64], [32, 48, 64]]
  set_abstraction2_cfg:
    npoint: 64
    radius_list: [0.2, 0.4, 0.8]
    nsample_list: [16, 32, 64]
    in_channel: 160
    mlp_list: [[32, 32, 64], [64, 64, 128], [64, 96, 128]]
  set_abstraction3_cfg:
    npoint:
    radius:
    nsample:
    in_channel: 323
    mlp: [256, 512, 1024]
    group_all: True
  hidden_dim: [512, 512]
pn_output_dim: 512

seq_len: 4

pose_tokenizer_cfg:
  hidden_dim: [64]
pose_token_dim: 64

# action_detokenizer_cfg:
#   cls_head_cfg: 
#     hidden_dim: [64]
#   rot_head_cfg:
#     hidden_dim: [512, 512, 64]
#     act_func: leaky_relu
#   trans_head_cfg:
#     hidden_dim: [256, 64]
#   open_head_cfg:
#     hidden_dim: [256, 64]
#   close_head_cfg:
#     hidden_dim: [256, 64]
state2action_ckpt: /data/jiangranlv/code/cutting_paper_fem/rloutputs/exp/fit_state2action/version_20/checkpoints/epoch=12-step=30000.ckpt
state2action_cfg:
  feat_dim: 128
  action_detokenizer_cfg:
    cls_head_cfg: 
      hidden_dim: []
    rot_head_cfg:
      hidden_dim: [64, 64]
      act_func: leaky_relu
    trans_head_cfg:
      hidden_dim: [64, 64]
    open_head_cfg:
      hidden_dim: [64, 64]
    close_head_cfg:
      hidden_dim: [64, 64]

goal_predictor_cfg:
  hidden_dim: [128, 64]

PE_cfg:
  dropout: 0.1
  max_len: 1000

transformer_cfg:
  layer:
    nhead: 8
    dim_feedforward: 256
  num_layers: 3

action_loss_cfg:
  rotation_dim: 18
  probability_weight: 0
  open_close_weight: 1e0
  translation_weight: 1e0
  rotation_weight: 1e0
  open_close_loss: l2
  translation_loss: huber
  rotation_loss: l1

use_helper: False
helper_net_cfg:
  npoints: 32
  hidden_dim: [256, 256]

helper_loss_cfg:
  loss_name: chamfer_distance
  weight: 1
  chamfer_distance_p: 1

goal_pred_offset: True
goal_pred_loss_cfg:
  weight: 1e1
  loss: l2

input_statistics: # old statistics
  point_cloud:
    mean: [0.08134385, 0.0046094, 0.15284023, 0.]
    std: [0.0735828, 0.0735828, 0.0735828, 1.]
  scissor_pose:
    mean: [-0.09131761, 0.02888361, 0.03622385, 0.14638498, 0.16358851, 0.0074226, 0.16835716, 0.14005724]
    std: [0.18268688, 0.10507938, 0.12708044, 0.0675601, 0.19768135, 0.20669429, 0.6547538, 0.6439879 ]
  action:
    translation:
      mean: [0.03259763, -0.00670006, 0.00247545]
      std: [0.04390685, 0.04390685, 0.04390685]
  front_point:
    mean: [0.073998,-0.002241 ,0.162374]
    std: [0.052029,0.004336,0.009971]
  cut_direction:
    mean: [0.947454,-0.046601,0.020884]
    std: [0.057117,0.100484,0.293878]
  next_edge:
    a:
      mean: [0.076762,-0.002724,0.162387]
      std: [0.02709,0.02709,0.02709]
    b:
      mean: [0.100298,-0.003954,0.162927]
      std: [0.023595,0.023595,0.023595]
